version: '3'
services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_USER: mysql_admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: pac_db
    volumes:
      - mysql-data:/var/lib/mysql

  react-app:
      build:
        context: ./vertical_inception_frontend
        dockerfile: Dockerfile
      ports:
        - "5000:80"

volumes:
  mysql-data: