version: '3'
services:
  mysql:
    image: mysql:8.0.34
    ports:
      - "23306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin1234
      MYSQL_USER: mysql_admin
      MYSQL_PASSWORD: admin1234
      MYSQL_DATABASE: pac_db
    volumes:
      - mysql-data:/var/lib/mysql

  spring-boot-app:
      build:
        context: ./vertical_inception_backend
        dockerfile: Dockerfile
      ports:
        - "8082:8082"
      depends_on:
        - mysql
      environment:
        SPRING_DATASOURCE_URL: jdbc:mysql://localhost:23306/pac_db
        SPRING_DATASOURCE_USERNAME: mysql_admin
        SPRING_DATASOURCE_PASSWORD: admin1234

  react-app:
      build:
        context: ./vertical_inception_frontend
        dockerfile: Dockerfile
      ports:
        - "5000:80"

volumes:
  mysql-data: